# -*- coding: utf-8 -*-
"""fotmerge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRzlV8EH4Be0eFKgGHiUJqfuO4fAdB0t
"""

import requests
import pandas as pd
import os
import csv

df = pd.DataFrame(pd.date_range(start='1/1/2000',
                                end='12/31/2022', freq='H'), columns=['Date'])
df2 = pd.DataFrame()

file_list = ['fot_00-06.xlsx', 'fot_07-100630.xlsx', 'fot_100701-13.xlsx', 'fot_14-20.xlsx', 'fot_21-22.xlsx']
print(file_list)
if os.path.exists("/content/fot.csv"):
  os.remove("/content/fot.csv")
for fot in file_list:
    Header_Row = 0
    data = pd.read_excel("/content/fot_master/" + str(fot))
    if "TID" in data.columns:
  #  temp = temp.to_csv("/content/sample_data/temp.csv")
        data['DATUM'] = data['DATUM'].astype(str)
        data['TID'] = data['TID'].astype(str)
        data['DATUM'] = data['DATUM'].str.zfill(8)
        data['TID'] = data['TID'].str.zfill(4)
        data['DATUM'] = data['DATUM'] + ' ' + data['TID']
        data['DATUM'] = pd.to_datetime(data['DATUM'], format='%Y%m%d %H%M')
        data = data.drop(['TID'],axis=1)
    else:
      # Convert the "DATUM" column to string
      data['DATUM'] = data['DATUM'].astype(str)

      # Convert the "DATUM" column to datetime using different formats
      data['DATUM_1'] = pd.to_datetime(data.loc[data['DATUM'].str.endswith('00:00'), 'DATUM'], format='%Y.%m.%d %H:%M:%S')
      data['DATUM_2'] = pd.to_datetime(data.loc[~data['DATUM'].str.endswith('00:00'), 'DATUM'], format='%d.%m.%Y %H:%M')
      # Combine the two subsets of the "DATUM" column
      data['DATUM'] = pd.concat([data['DATUM_1'], data['DATUM_2']], ignore_index=True)

      # Drop the intermediate columns
      data.drop(['DATUM_1', 'DATUM_2'], axis=1, inplace=True)
      #data['DATUM'] = pd.to_datetime(data['DATUM'], format='%d.%m.%Y %H:%M')
    data.rename(
      columns={'DATUM': 'Date'}, inplace=True)
    print("Done with " + fot)
#     temporary.drop(['Datum', 'Tid (UTC)'], axis=1, inplace=True)
#     temporary = temporary[~(temporary['Date'] < '2000-01-01')]
    df = pd.concat([df, data], ignore_index=True)
    df.sort_values(by=['Date'], inplace=True)
    #print(data)
    data.to_csv("/content/fot.csv", index=False, mode = "a", header = not os.path.exists("/content/fot.csv"))
# df.to_csv("/content/fot.csv", index=False)
#print(df)

